package com.summsoft.vistas;

import com.summsoft.implementaciones.ImplTipoBus;
import com.summsoft.implementaciones.TarifaImpl;
import com.summsoft.interfases.DaoTipoBus;
import com.summsoft.interfases.TarifaDao;
import com.summsoft.modelos.Plantilla;
import com.summsoft.modelos.Tarifa;
import com.summsoft.modelos.Venta;
import com.summsoft.utilerias.Boletos;
import com.summsoft.utilerias.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VentaView extends javax.swing.JInternalFrame {

    //obtenemos las tarifas
    private List<Tarifa> tarifas;
    DefaultComboBoxModel modeloDestino;
    String tipo = "sencillo";
    String parametro = "nulo";
    String Abrev = null;
    String TipoBoleto = null;
    int Costo;
    int totalVenta;

    //obtenemos los asientos
    DaoTipoBus dao = new ImplTipoBus();
    List<Plantilla> mdl = dao.bus(Boletos.getFolio());

    private List<Venta> Ventas;

    public VentaView() throws Exception {
        modeloDestino = new DefaultComboBoxModel(new String[]{});
        tarifas = new ArrayList<>();
        initComponents();
        Tarifas();
        Destinos();
        inicio();
        mostrarBus();
        txtAsiento.requestFocus();
        this.getRootPane().setDefaultButton(btnIntegrar);
    }

    private void mostrarBus() throws Exception {
        int cols = 5;
        DefaultTableModel model = (DefaultTableModel) tblAutobus.getModel();
        model.setRowCount(0); // Limpia todas las filas existentes
        Object[] rowData = new Object[cols]; // Array para almacenar los 5 valores
        int colIndex = 0;

        for (Plantilla bus : mdl) {
            rowData[colIndex] = bus.getBoleto(); // Agrega el valor al array
            colIndex++;

            // Si el array está lleno, agregamos la fila y reseteamos el índice
            if (colIndex == cols) {
                model.addRow(rowData); // Añade la fila con 5 valores
                rowData = new Object[cols]; // Resetea el array
                colIndex = 0;
            }
        }

// Si quedaron valores sin completar una fila, los añadimos igual
        if (colIndex > 0) {
            model.addRow(rowData); // Añade la última fila incompleta si es necesario
        }

// Ajusta la altura de las filas a 30 píxeles (puedes cambiar este valor)
        tblAutobus.setRowHeight(30);

    }

    private void Tarifas() throws Exception {
        TarifaDao dao = new TarifaImpl();
        tarifas = dao.tarifas(Boletos.getRuta());
    }

    private void Destinos() {
        try {
            TarifaDao dao = new TarifaImpl();
            List<Tarifa> destinos = dao.destinos(Boletos.getRuta());

            for (Tarifa term : destinos) {

                modeloDestino.addElement(term.getDestino());
            }
        } catch (Exception e) {
            System.out.println("error " + e);
        }
    }

    private void inicio() {

        txtOrigen.setText(Usuario.terminal);
        btnSencillo.doClick();
        txtFolio.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutobus = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        jcDestino = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtAsiento = new javax.swing.JTextField();
        btnSencillo = new javax.swing.JButton();
        btnInsen = new javax.swing.JButton();
        btnNino = new javax.swing.JButton();
        btnEducativo = new javax.swing.JButton();
        btnRedondo = new javax.swing.JButton();
        btnDescuento = new javax.swing.JButton();
        btnRegreso = new javax.swing.JButton();
        btnPase = new javax.swing.JButton();
        txtExcedente = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        btnExcedente = new javax.swing.JButton();
        btnOrganizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        lblParametro = new javax.swing.JLabel();
        btnIntegrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVenta = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();

        setTitle("Venta de Boletos EXAL");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/boletoMnu.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Autobus"));

        tblAutobus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Col 1", "Col 2", "Col 3", "Col 4", "Col 5"
            }
        ));
        jScrollPane1.setViewportView(tblAutobus);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del boleto"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Origen");

        jcDestino.setModel(modeloDestino);
        jcDestino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcDestinoFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Destino");

        btnSencillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.png"))); // NOI18N
        btnSencillo.setMnemonic('1');
        btnSencillo.setText("Sencillo");
        btnSencillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSencilloActionPerformed(evt);
            }
        });

        btnInsen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.png"))); // NOI18N
        btnInsen.setMnemonic('2');
        btnInsen.setText("INSEN");
        btnInsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsenActionPerformed(evt);
            }
        });

        btnNino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.png"))); // NOI18N
        btnNino.setMnemonic('3');
        btnNino.setText("Niño");
        btnNino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNinoActionPerformed(evt);
            }
        });

        btnEducativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/4.png"))); // NOI18N
        btnEducativo.setMnemonic('4');
        btnEducativo.setText("Educativo");
        btnEducativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEducativoActionPerformed(evt);
            }
        });

        btnRedondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redondo.png"))); // NOI18N
        btnRedondo.setMnemonic('R');
        btnRedondo.setText("Redondo");
        btnRedondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedondoActionPerformed(evt);
            }
        });

        btnDescuento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/descuento.png"))); // NOI18N
        btnDescuento.setMnemonic('D');
        btnDescuento.setText("Descuento");
        btnDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescuentoActionPerformed(evt);
            }
        });

        btnRegreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        btnRegreso.setMnemonic('E');
        btnRegreso.setText("Regreso");
        btnRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresoActionPerformed(evt);
            }
        });

        btnPase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pase.png"))); // NOI18N
        btnPase.setMnemonic('P');
        btnPase.setText("Pase");
        btnPase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaseActionPerformed(evt);
            }
        });

        txtExcedente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtExcedente.setText("0");

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblPrecio.setText("$");

        btnExcedente.setMnemonic('X');
        btnExcedente.setText("Excedente");
        btnExcedente.setToolTipText("");
        btnExcedente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcedenteActionPerformed(evt);
            }
        });

        btnOrganizar.setMnemonic('a');
        btnOrganizar.setText("Asiento");
        btnOrganizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganizarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Folio:");

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipo.setText("_");

        lblParametro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblParametro.setText("_");

        btnIntegrar.setText("Integrar");
        btnIntegrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntegrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIntegrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnOrganizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSencillo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(btnInsen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExcedente)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnRedondo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRegreso))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtExcedente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(lblParametro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jcDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnNino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnEducativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnPase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSencillo)
                            .addComponent(btnInsen)
                            .addComponent(btnNino))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRedondo)
                            .addComponent(btnDescuento)
                            .addComponent(btnRegreso))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnOrganizar))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipo)
                            .addComponent(lblParametro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtExcedente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcedente)
                            .addComponent(lblPrecio)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEducativo)
                        .addGap(18, 18, 18)
                        .addComponent(btnPase)
                        .addGap(18, 18, 18)
                        .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIntegrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));

        tblVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Folio", "Destino", "Boleto", "Tipo", "Costo", "Exc.", "Total"
            }
        ));
        jScrollPane2.setViewportView(tblVenta);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("_");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTotal)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrganizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganizarActionPerformed

        String origen = txtOrigen.getText();
        String destino = jcDestino.getSelectedItem().toString();

        for (Tarifa tarifa : tarifas) {
            if (tarifa.getOrigen().equalsIgnoreCase(origen) && tarifa.getDestino().equalsIgnoreCase(destino)) {
                Abrev = tarifa.getAbrev();
                if (tipo.equals("sencillo")) {
                    lblPrecio.setText("$ " + tarifa.getSencillo());
                    Costo=tarifa.getSencillo();
                    TipoBoleto = "Sencillo";
                }
                if (tipo.equals("nino")) {
                    lblPrecio.setText("$ " + tarifa.getNino());
                    TipoBoleto = "Niño";
                    Costo=tarifa.getNino();
                }
                if (tipo.equals("insen")) {
                    lblPrecio.setText("$ " + tarifa.getInsen());
                    TipoBoleto = "INSEN";
                    Costo=tarifa.getInsen();
                }
                if (tipo.equals("estudiante")) {
                    lblPrecio.setText("$ " + tarifa.getEstudiante());
                    TipoBoleto = "Estudiante";
                    Costo=tarifa.getEstudiante();
                }
                if (tipo.equals("redondo")) {
                    lblPrecio.setText("$ " + tarifa.getRedondo());
                    TipoBoleto = "Redondo";
                    Costo=tarifa.getRedondo();
                }
                if ((tipo.equals("redondo") && (lblParametro.getText().equals("Descuento")))) {
                    lblPrecio.setText("$ " + tarifa.getRedondo_desc());
                    TipoBoleto = "Red. Desc.";
                    Costo=tarifa.getRedondo_desc();
                }
                if ((tipo.equals("nino") && (lblParametro.getText().equals("Descuento")))) {
                    lblPrecio.setText("$ " + tarifa.getNino_desc());
                    TipoBoleto = "Niño Desc.";
                    Costo=tarifa.getNino_desc();
                }
                if (lblParametro.getText().equals("Pase")) {
                    lblPrecio.setText("$ 0.00");
                    TipoBoleto = "Pase";
                    Costo=0;
                }
                if (tipo.equals("pasillo")) {
                    lblPrecio.setText("$ " + tarifa.getPasillo());
                    TipoBoleto = "Pasillo";
                    Costo=tarifa.getPasillo();
                }
                if (tipo.equals("regreso")) {
                    lblPrecio.setText("$ 0.0");
                    TipoBoleto = "Regreso";
                    Costo=0;
                }
            }
        }
        txtAsiento.requestFocus();
    }//GEN-LAST:event_btnOrganizarActionPerformed

    private void btnInsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsenActionPerformed
        tipo = "insen";
        btnOrganizar.doClick();
        lblTipo.setText("INSEN");
    }//GEN-LAST:event_btnInsenActionPerformed

    private void btnNinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNinoActionPerformed
        tipo = "nino";
        btnOrganizar.doClick();
        lblTipo.setText("Niño");
        lblParametro.setText("_");
        parametro="nulo";
    }//GEN-LAST:event_btnNinoActionPerformed

    private void btnSencilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSencilloActionPerformed
        tipo = "sencillo";
        btnSencillo.putClientProperty("JButton.pressedBackground", Color.ORANGE);
        lblTipo.setText("Sencillo");
        lblParametro.setText("_");
        txtFolio.setEnabled(false);
        txtFolio.setText("");
        txtExcedente.setText("0");
        btnOrganizar.doClick();
    }//GEN-LAST:event_btnSencilloActionPerformed

    private void btnEducativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEducativoActionPerformed
        tipo = "estudiante";
        btnOrganizar.doClick();
        lblTipo.setText("Educativo");
    }//GEN-LAST:event_btnEducativoActionPerformed

    private void btnRedondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedondoActionPerformed
        tipo = "redondo";
        parametro="nulo";
        btnOrganizar.doClick();
        lblTipo.setText("Redondo");
        lblParametro.setText("_");
    }//GEN-LAST:event_btnRedondoActionPerformed

    private void btnRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresoActionPerformed
        tipo = "regreso";
        btnOrganizar.doClick();
        lblTipo.setText("Regreso");
        txtFolio.setEnabled(true);
        txtFolio.requestFocus();
    }//GEN-LAST:event_btnRegresoActionPerformed

    private void btnDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescuentoActionPerformed
        parametro = "descuento";
        lblParametro.setText("Descuento");
        btnOrganizar.doClick();
    }//GEN-LAST:event_btnDescuentoActionPerformed

    private void btnPaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaseActionPerformed
        parametro = "pase";
        lblParametro.setText("Pase");
        btnOrganizar.doClick();
    }//GEN-LAST:event_btnPaseActionPerformed

    private void btnExcedenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcedenteActionPerformed
        txtExcedente.requestFocus();
    }//GEN-LAST:event_btnExcedenteActionPerformed

    private void btnIntegrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntegrarActionPerformed
        String asiento = txtAsiento.getText();
        if (asiento.equals("")) {
            txtAsiento.requestFocus();
        } else {
            boolean disponible = false;
            // Buscar y reemplazar un valor basado en el campo `valor`
            String nuevoAsiento = Abrev; // Nuevo asiento a asignar

            for (Plantilla bus : mdl) {
                if (bus.getBoleto().equals(asiento)) {
                    disponible = true;
                    bus.setBoleto(nuevoAsiento);  // Reemplazar asiento
                    break;  // Salir del bucle si solo deseas actualizar el primero que coincida
                }
            }

            if (disponible) {
                String folio = Boletos.getFolio();
                if(tipo.equals("regreso")) folio=txtFolio.getText();
                String boleto = Usuario.getAbrev() + txtAsiento.getText();
                String precio = lblPrecio.getText();
                String exc = txtExcedente.getText();

                try {
                    int Excedente = exc.isEmpty() ? 0 : Integer.parseInt(exc);   // Verifica si `exc` está vacío
                    String total = String.valueOf(Costo + Excedente);

                    DefaultTableModel tmVenta = (DefaultTableModel) tblVenta.getModel();
                    tmVenta.addRow(new Object[]{
                        folio, Abrev, boleto, TipoBoleto, precio, exc, total
                    });
                    totalVenta+=Integer.valueOf(total);
                    lblTotal.setText("Venta Total $"+totalVenta);

                } catch (NumberFormatException e) {
                    System.out.println("Error de formato numérico: " + e.getMessage());
                } catch (Exception e) {
                    System.out.println("Otro error: " + e.getMessage());
                }

                try {
                    mostrarBus();
                } catch (Exception ex) {
                    System.out.println("error " + ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecciona una opcion valida", "Advertencia", JOptionPane.WARNING_MESSAGE);
            }
            txtAsiento.setText("");
            txtExcedente.setText("0");
            txtAsiento.requestFocus();
            txtFolio.setText("");
            txtFolio.setEnabled(false);
        }
    }//GEN-LAST:event_btnIntegrarActionPerformed

    private void jcDestinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcDestinoFocusLost
       btnSencillo.doClick();
    }//GEN-LAST:event_jcDestinoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescuento;
    private javax.swing.JButton btnEducativo;
    private javax.swing.JButton btnExcedente;
    private javax.swing.JButton btnInsen;
    private javax.swing.JButton btnIntegrar;
    private javax.swing.JButton btnNino;
    private javax.swing.JButton btnOrganizar;
    private javax.swing.JButton btnPase;
    private javax.swing.JButton btnRedondo;
    private javax.swing.JButton btnRegreso;
    private javax.swing.JButton btnSencillo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcDestino;
    private javax.swing.JLabel lblParametro;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblAutobus;
    private javax.swing.JTable tblVenta;
    private javax.swing.JTextField txtAsiento;
    private javax.swing.JTextField txtExcedente;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
