
package com.summsoft.vistas;

import com.summsoft.implementaciones.VentaImpl;
import com.summsoft.interfases.VentaDao;
import com.summsoft.modelos.Venta;
import com.summsoft.utilerias.Boletos;
import com.summsoft.utilerias.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;


public class VentaView extends javax.swing.JInternalFrame {
   private List<Venta> tarifas;
   DefaultComboBoxModel modeloDestino;
   String tipo="sencillo";
    public VentaView() throws Exception {
        modeloDestino = new DefaultComboBoxModel(new String[]{});
        tarifas = new ArrayList<>();
        initComponents();
        Tarifas();
        inicio();
        Destinos();
    }
    
    private void Tarifas() throws Exception{
        VentaDao dao = new VentaImpl();
        tarifas = dao.tarifas(Boletos.getRuta());
    }
    
    private void Destinos(){
        try {

            VentaDao dao = new VentaImpl();
            List<Venta> destinos = dao.destinos(Boletos.getRuta());

            for (Venta term : destinos) {
                
                modeloDestino.addElement(term.getDestino());
            }
        } catch (Exception e) {
            System.out.println("error " + e);
        }
    }
    private void inicio(){
        
        txtOrigen.setText(Usuario.terminal);
        
        
        
//         // Mapeo de teclas
//        InputMap inputMap = txtNumeroBoleto.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
//        ActionMap actionMap = txtNumeroBoleto.getActionMap();
//
//        // F1 para tipo Sencillo
//        inputMap.put(KeyStroke.getKeyStroke("F1"), "tipoSencillo");
//        actionMap.put("tipoSencillo", new AbstractAction() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                lblCategoria.setText("Categoría: Sencillo");
//            }
//        });
//        
//        // F2 para tipo Niño
//        inputMap.put(KeyStroke.getKeyStroke("F2"), "tipoNino");
//        actionMap.put("tipoNino", new AbstractAction() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                lblCategoria.setText("Categoría: Niño");
//            }
//        });
//        
//        // F3 para tipo Descuento
//        inputMap.put(KeyStroke.getKeyStroke("F3"), "tipoDescuento");
//        actionMap.put("tipoDescuento", new AbstractAction() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                lblCategoria.setText("Categoría: Descuento");
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutobus = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        jcDestino = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtAsiento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblDatosBoleto = new javax.swing.JLabel();
        btnSencillo = new javax.swing.JButton();
        btnInsen = new javax.swing.JButton();
        btnNino = new javax.swing.JButton();
        btnEducativo = new javax.swing.JButton();
        btnRedondo = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btnVender = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setTitle("Venta de Boletos EXAL");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/boletoMnu.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Autobus"));

        tblAutobus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Col 1", "Col 2", "Col 3", "Col 4", "Col 5"
            }
        ));
        jScrollPane1.setViewportView(tblAutobus);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del boleto"));

        jLabel1.setText("Origen");

        jcDestino.setModel(modeloDestino);

        jLabel2.setText("Destino");

        jLabel4.setText("Tipo de boleto:");

        lblDatosBoleto.setText("_");

        btnSencillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.png"))); // NOI18N
        btnSencillo.setMnemonic('1');
        btnSencillo.setText("Sencillo");
        btnSencillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSencilloActionPerformed(evt);
            }
        });

        btnInsen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.png"))); // NOI18N
        btnInsen.setMnemonic('2');
        btnInsen.setText("INSEN");
        btnInsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsenActionPerformed(evt);
            }
        });

        btnNino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.png"))); // NOI18N
        btnNino.setMnemonic('3');
        btnNino.setText("Niño");
        btnNino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNinoActionPerformed(evt);
            }
        });

        btnEducativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/4.png"))); // NOI18N
        btnEducativo.setMnemonic('4');
        btnEducativo.setText("Educativo");
        btnEducativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEducativoActionPerformed(evt);
            }
        });

        btnRedondo.setText("Redondo");
        btnRedondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedondoActionPerformed(evt);
            }
        });

        jButton9.setText("Descuento");

        jButton10.setText("Regreso");

        jButton11.setText("Pase");

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblPrecio.setText("$");

        jButton1.setMnemonic('a');
        jButton1.setText("Asiento:");

        jButton8.setMnemonic('E');
        jButton8.setText("Excedente");
        jButton8.setToolTipText("");

        btnVender.setText("V");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(lblDatosBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButton8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnRedondo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10)))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 12, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(btnVender)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSencillo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInsen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEducativo)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSencillo)
                    .addComponent(btnInsen)
                    .addComponent(btnNino)
                    .addComponent(btnEducativo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRedondo)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnVender))
                .addGap(18, 18, 18)
                .addComponent(lblDatosBoleto)
                .addGap(32, 32, 32))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        
        String origen=txtOrigen.getText();
        String destino=jcDestino.getSelectedItem().toString();
        
        for (Venta tarifa : tarifas) {
            if (tarifa.getOrigen().equalsIgnoreCase(origen) && tarifa.getDestino().equalsIgnoreCase(destino)) {
                if (tipo.equals("sencillo"))lblPrecio.setText("$ "+tarifa.getSencillo() );
                if (tipo.equals("nino"))lblPrecio.setText("$ "+tarifa.getNino() );
                if (tipo.equals("insen"))lblPrecio.setText("$ "+tarifa.getInsen() );
                if (tipo.equals("estudiante"))lblPrecio.setText("$ "+tarifa.getEstudiante() );
                if (tipo.equals("redondo"))lblPrecio.setText("$ "+tarifa.getRedondo() );
            }
        }
        
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnInsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsenActionPerformed
        tipo="insen";
        btnVender.doClick();
    }//GEN-LAST:event_btnInsenActionPerformed

    private void btnNinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNinoActionPerformed
        tipo="nino";
        btnVender.doClick();
    }//GEN-LAST:event_btnNinoActionPerformed

    private void btnSencilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSencilloActionPerformed
        tipo="sencillo";
        btnVender.doClick();
        btnSencillo.putClientProperty("JButton.pressedBackground", Color.ORANGE);  // Color cuando se presiona
    }//GEN-LAST:event_btnSencilloActionPerformed

    private void btnEducativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEducativoActionPerformed
        tipo="estudiante";
        btnVender.doClick();
    }//GEN-LAST:event_btnEducativoActionPerformed

    private void btnRedondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedondoActionPerformed
        tipo="redondo";
        btnVender.doClick();
    }//GEN-LAST:event_btnRedondoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEducativo;
    private javax.swing.JButton btnInsen;
    private javax.swing.JButton btnNino;
    private javax.swing.JButton btnRedondo;
    private javax.swing.JButton btnSencillo;
    private javax.swing.JButton btnVender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jcDestino;
    private javax.swing.JLabel lblDatosBoleto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JTable tblAutobus;
    private javax.swing.JTextField txtAsiento;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
