package com.summsoft.vistas;

import com.summsoft.implementaciones.ImplTipoBus;
import com.summsoft.implementaciones.VentaImpl;
import com.summsoft.interfases.DaoTipoBus;
import com.summsoft.interfases.VentaDao;
import com.summsoft.modelos.MdlTipoBus;
import com.summsoft.modelos.Venta;
import com.summsoft.utilerias.Boletos;
import com.summsoft.utilerias.CustomCellRenderer;
import com.summsoft.utilerias.Usuario;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

public class VentaView extends javax.swing.JInternalFrame {

    private List<Venta> tarifas;
    DefaultComboBoxModel modeloDestino;
    String tipo = "sencillo";
    String parametro = "nulo";

    public VentaView() throws Exception {
        modeloDestino = new DefaultComboBoxModel(new String[]{});
        tarifas = new ArrayList<>();
        initComponents();
        Tarifas();
        Destinos();
        inicio();

        mostrarBus();
    }

    private void mostrarBus() throws Exception {
        DaoTipoBus dao = new ImplTipoBus();
        List<MdlTipoBus> mdl = dao.bus(Boletos.getBus());

        int cols = 5;
        DefaultTableModel model = (DefaultTableModel) tblAutobus.getModel();
        Object[] rowData = new Object[cols]; // Array para almacenar los 5 valores
        int colIndex = 0;

        for (MdlTipoBus bus : mdl) {
            rowData[colIndex] = bus.getValor(); // Agrega el valor al array
            colIndex++;

            // Si el array está lleno, agregamos la fila y reseteamos el índice
            if (colIndex == cols) {
                model.addRow(rowData); // Añade la fila con 5 valores
                rowData = new Object[cols]; // Resetea el array
                colIndex = 0;
            }
        }

// Si quedaron valores sin completar una fila, los añadimos igual
        if (colIndex > 0) {
            model.addRow(rowData); // Añade la última fila incompleta si es necesario
        }

// Ajusta la altura de las filas a 30 píxeles (puedes cambiar este valor)
        tblAutobus.setRowHeight(30);

// Crea una instancia del renderer personalizado
        CustomCellRenderer renderer = new CustomCellRenderer();

// Asigna el renderer a todas las columnas de la tabla
        for (int i = 0; i < tblAutobus.getColumnCount(); i++) {
            tblAutobus.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }

    }

    
    
    private void Tarifas() throws Exception {
        VentaDao dao = new VentaImpl();
        tarifas = dao.tarifas(Boletos.getRuta());
    }

    private void Destinos() {
        try {

            VentaDao dao = new VentaImpl();
            List<Venta> destinos = dao.destinos(Boletos.getRuta());

            for (Venta term : destinos) {

                modeloDestino.addElement(term.getDestino());
            }
        } catch (Exception e) {
            System.out.println("error " + e);
        }
    }

    private void inicio() {

        txtOrigen.setText(Usuario.terminal);
        btnSencillo.doClick();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutobus = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        jcDestino = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtAsiento = new javax.swing.JTextField();
        lblDatosBoleto = new javax.swing.JLabel();
        btnSencillo = new javax.swing.JButton();
        btnInsen = new javax.swing.JButton();
        btnNino = new javax.swing.JButton();
        btnEducativo = new javax.swing.JButton();
        btnRedondo = new javax.swing.JButton();
        btnDescuento = new javax.swing.JButton();
        btnRegreso = new javax.swing.JButton();
        btnPase = new javax.swing.JButton();
        txtExcedente = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        btnExcedente = new javax.swing.JButton();
        btnVender = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        lblParametro = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setTitle("Venta de Boletos EXAL");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/boletoMnu.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Autobus"));

        tblAutobus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Col 1", "Col 2", "Col 3", "Col 4", "Col 5"
            }
        ));
        jScrollPane1.setViewportView(tblAutobus);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del boleto"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Origen");

        jcDestino.setModel(modeloDestino);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Destino");

        lblDatosBoleto.setText("_");

        btnSencillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.png"))); // NOI18N
        btnSencillo.setMnemonic('1');
        btnSencillo.setText("Sencillo");
        btnSencillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSencilloActionPerformed(evt);
            }
        });

        btnInsen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.png"))); // NOI18N
        btnInsen.setMnemonic('2');
        btnInsen.setText("INSEN");
        btnInsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsenActionPerformed(evt);
            }
        });

        btnNino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.png"))); // NOI18N
        btnNino.setMnemonic('3');
        btnNino.setText("Niño");
        btnNino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNinoActionPerformed(evt);
            }
        });

        btnEducativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/4.png"))); // NOI18N
        btnEducativo.setMnemonic('4');
        btnEducativo.setText("Educativo");
        btnEducativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEducativoActionPerformed(evt);
            }
        });

        btnRedondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/redondo.png"))); // NOI18N
        btnRedondo.setMnemonic('R');
        btnRedondo.setText("Redondo");
        btnRedondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedondoActionPerformed(evt);
            }
        });

        btnDescuento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/descuento.png"))); // NOI18N
        btnDescuento.setMnemonic('D');
        btnDescuento.setText("Descuento");
        btnDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescuentoActionPerformed(evt);
            }
        });

        btnRegreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        btnRegreso.setMnemonic('E');
        btnRegreso.setText("Regreso");
        btnRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresoActionPerformed(evt);
            }
        });

        btnPase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pase.png"))); // NOI18N
        btnPase.setMnemonic('P');
        btnPase.setText("Pase");
        btnPase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaseActionPerformed(evt);
            }
        });

        txtExcedente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtExcedente.setText("0");

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblPrecio.setText("$");

        btnExcedente.setMnemonic('X');
        btnExcedente.setText("Excedente");
        btnExcedente.setToolTipText("");
        btnExcedente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcedenteActionPerformed(evt);
            }
        });

        btnVender.setText("Asiento");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Folio:");

        txtFolio.setEditable(false);

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTipo.setText("_");

        lblParametro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblParametro.setText("_");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDatosBoleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnVender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSencillo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(btnInsen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExcedente)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnRedondo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRegreso))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtExcedente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(lblParametro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jcDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnNino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnEducativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnPase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSencillo)
                            .addComponent(btnInsen)
                            .addComponent(btnNino))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRedondo)
                            .addComponent(btnDescuento)
                            .addComponent(btnRegreso))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnVender))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipo)
                            .addComponent(lblParametro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtExcedente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcedente)
                            .addComponent(lblPrecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(lblDatosBoleto)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEducativo)
                        .addGap(18, 18, 18)
                        .addComponent(btnPase)
                        .addGap(18, 18, 18)
                        .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Total"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed

        String origen = txtOrigen.getText();
        String destino = jcDestino.getSelectedItem().toString();

        for (Venta tarifa : tarifas) {
            if (tarifa.getOrigen().equalsIgnoreCase(origen) && tarifa.getDestino().equalsIgnoreCase(destino)) {
                if (tipo.equals("sencillo")) {
                    lblPrecio.setText("$ " + tarifa.getSencillo());
                }
                if (tipo.equals("nino")) {
                    lblPrecio.setText("$ " + tarifa.getNino());
                }
                if (tipo.equals("insen")) {
                    lblPrecio.setText("$ " + tarifa.getInsen());
                }
                if (tipo.equals("estudiante")) {
                    lblPrecio.setText("$ " + tarifa.getEstudiante());
                }
                if (tipo.equals("redondo")) {
                    lblPrecio.setText("$ " + tarifa.getRedondo());
                }
                if ((tipo.equals("redondo") && (lblParametro.getText().equals("Descuento")))) {
                    lblPrecio.setText("$ " + tarifa.getRedondo_desc());
                }
                if ((tipo.equals("nino") && (lblParametro.getText().equals("Descuento")))) {
                    lblPrecio.setText("$ " + tarifa.getNino_desc());
                }
                if (lblParametro.getText().equals("Pase")) {
                    lblPrecio.setText("$ 0.00");
                }
            }
        }

    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnInsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsenActionPerformed
        tipo = "insen";
        btnVender.doClick();
        lblTipo.setText("INSEN");
    }//GEN-LAST:event_btnInsenActionPerformed

    private void btnNinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNinoActionPerformed
        tipo = "nino";
        btnVender.doClick();
        lblTipo.setText("Niño");
    }//GEN-LAST:event_btnNinoActionPerformed

    private void btnSencilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSencilloActionPerformed
        tipo = "sencillo";
        btnSencillo.putClientProperty("JButton.pressedBackground", Color.ORANGE);
        lblTipo.setText("Sencillo");
        lblParametro.setText("_");
        txtFolio.setEnabled(false);
        txtFolio.setText("");
        txtExcedente.setText("0");
        btnVender.doClick();
    }//GEN-LAST:event_btnSencilloActionPerformed

    private void btnEducativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEducativoActionPerformed
        tipo = "estudiante";
        btnVender.doClick();
        lblTipo.setText("Educativo");
    }//GEN-LAST:event_btnEducativoActionPerformed

    private void btnRedondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedondoActionPerformed
        tipo = "redondo";
        btnVender.doClick();
        lblTipo.setText("Redondo");
    }//GEN-LAST:event_btnRedondoActionPerformed

    private void btnRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresoActionPerformed
        tipo = "regreso";
        btnVender.doClick();
        lblTipo.setText("Regreso");
        txtFolio.setEnabled(true);
        txtFolio.requestFocus();
    }//GEN-LAST:event_btnRegresoActionPerformed

    private void btnDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescuentoActionPerformed
        parametro = "descuento";
        lblParametro.setText("Descuento");
        btnVender.doClick();
    }//GEN-LAST:event_btnDescuentoActionPerformed

    private void btnPaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaseActionPerformed
        parametro = "pase";
        lblParametro.setText("Pase");
        btnVender.doClick();
    }//GEN-LAST:event_btnPaseActionPerformed

    private void btnExcedenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcedenteActionPerformed
        txtExcedente.requestFocus();
    }//GEN-LAST:event_btnExcedenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescuento;
    private javax.swing.JButton btnEducativo;
    private javax.swing.JButton btnExcedente;
    private javax.swing.JButton btnInsen;
    private javax.swing.JButton btnNino;
    private javax.swing.JButton btnPase;
    private javax.swing.JButton btnRedondo;
    private javax.swing.JButton btnRegreso;
    private javax.swing.JButton btnSencillo;
    private javax.swing.JButton btnVender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcDestino;
    private javax.swing.JLabel lblDatosBoleto;
    private javax.swing.JLabel lblParametro;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTable tblAutobus;
    private javax.swing.JTextField txtAsiento;
    private javax.swing.JTextField txtExcedente;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
